In [17]:
text = ("Trust me, though, the words were on their way, and when "
        "they arrived, Liesel would hold them in her hands like "
        "the clouds, and she would wring them out, like the rain.")
tokens = text.split()
tokens[:8]

['Trust', 'me,', 'though,', 'the', 'words', 'were', 'on', 'their']

In [18]:
import re
pattern = r'\w+(?:\'\w+)?|[^\w\s]' #(?:\'\w+)? detects whether the word contains a single apostrophe followed by one or more letters
    #can accommodate double contractions with r'\w+(?:\'\w+){0,2}|[^\w\s]'
texts = [text]
texts.append("There's no such thing as survival of the fittest. Survival of the most adequate, maybe.")
tokens = list(re.findall(pattern, texts[-1]))
tokens[:8]

["There's", 'no', 'such', 'thing', 'as', 'survival', 'of', 'the']

In [22]:
tokens[8:16]

['=', '"', 'en', '"', '>', '<', 'head', '>']

In [26]:
tokens[16:]

['maybe', '.']

In [19]:
import numpy as np
vocab = sorted(set(tokens)) #coerce the list into a set so that vocabulary contains only unique tokens
' '.join(vocab[:12]) #sorts lexicographically so the order is punctuation, capitalized, lowercase

", . Survival There's adequate as fittest maybe most no of such"

In [28]:
num_tokens = len(tokens)
num_tokens

18

In [20]:
vocab_size = len(vocab)
vocab_size

15

In [21]:
import spacy
#spacy.cli.download('en_core_web_sm') #运行出错，显示404，手动下载文件放入site-packages
nlp = spacy.load('en_core_web_sm') #sm stands for small, md=medium, lg=large
doc = nlp(texts[-1])
type(doc)

AttributeError: partially initialized module 'torch' has no attribute 'fx' (most likely due to a circular import)

In [ ]:
tokens = [tok.text for tok in doc]
tokens[:9]

In [ ]:
tokens[9:17]

In [33]:
from spacy import displacy
sentence = list(doc.sents)[0]
svg = displacy.render(sentence, style="dep", jupyter=False)
open('sentence_diagram.svg', 'w').write(svg)
# displacy.serve(sentence, style="dep")
# !firefox 127.0.0.1:5000
displacy.render(sentence, style="dep")

In [34]:
import requests
text = requests.get('https://proai.org/nlpia2-ch2.adoc').text #ConnectTimeout
#text = requests.get('https://cgtn.com').text
f'{round(len(text) / 10_1000)}0k'

'20k'

In [40]:
%timeit nlp(text)

6.01 s ± 146 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]:
f'{round(len(text) / 10_000)}0k'

'190k'

In [37]:
doc = nlp(text)
f'{round(len(list(doc)) / 10_000)}0k'

'40k'

In [38]:
f'{round(len(doc) / 1_000 / 10.4)}kWPS' #kWPS is for thousands of words per second

'4kWPS'

In [39]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [41]:
nlp = spacy.load('en_core_web_sm', disable=nlp.pipe_names) #disable spaCy pipeline to get faster
%timeit nlp(text)

439 ms ± 4.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [42]:
import nltk
#nltk.download('punkt')
from nltk.tokenize import word_tokenize
%timeit word_tokenize(text)

286 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [43]:
tokens = word_tokenize(text)
f'{round(len(tokens) / 10_000)}0k'

'40k'

In [44]:
pattern = r'\w+(?:\'\w+)?|[^\w\s]'
tokens = re.findall(pattern, text)
f'{round(len(tokens) / 10_000)}0k'

'40k'

In [45]:
%timeit re.findall(pattern, text)

16.1 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [46]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(ngram_range=(1, 2), analyzer='char')
vectorizer.fit(texts)

CountVectorizer(analyzer='char', ngram_range=(1, 2))

In [47]:
bpevocab_list = [sorted((i, s) for s, i in vectorizer.vocabulary_.items())]
bpevocab_dict = dict(bpevocab_list[0])
list(bpevocab_dict.values())[:7]

[' ', ' a', ' c', ' f', ' h', ' i', ' l']

In [48]:
vectors = vectorizer.transform(texts)
df = pd.DataFrame(vectors.todense(), columns=vectorizer.get_feature_names_out())
df.index = [t[:8] + '...' for t in texts]
df = df.T
df['total'] = df.T.sum()
df

    Trust me...  There's ...  total
             31           14     45
 a            3            2      5
 c            1            0      1
 f            0            1      1
 h            3            0      3
..          ...          ...    ...
wr            1            0      1
y             2            1      3
y             1            0      1
y,            1            0      1
yb            0            1      1

[148 rows x 3 columns]

In [49]:
df.sort_values('total').tail()

    Trust me...  There's ...  total
he           10            3     13
h            14            5     19
t            11            9     20
e            18            8     26
             31           14     45

In [50]:
df['n'] = [len(tok) for tok in vectorizer.vocabulary_]
df[df['n'] > 1].sort_values('total').tail()

    Trust me...  There's ...  total  n
th            8            4     12  2
he           10            3     13  2
h            14            5     19  2
t            11            9     20  2
e            18            8     26  2

In [52]:
import requests
url = ("https://gitlab.com/tangibleai/nlpia/-/raw/master/src/nlpia/data/stopword_lists.json")
response = requests.get(url)
stopwords = response.json()['exhaustive']
tokens = 'the words were just as I remembered them'.split()
tokens_without_stopwords = [x for x in tokens if x not in stopwords]
print(tokens_without_stopwords)

['I', 'remembered']

In [54]:
import nltk
nltk.download('stopwords')
stop_words = nltk.corpus.stopwords.words('english')
len(stop_words)

[nltk_data] Downloading package stopwords to C:\Users\throw\Study\Mini
[nltk_data]     conda\miniconda3\envs\nlpia2\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

198

In [55]:
stop_words[:7]

['a', 'about', 'above', 'after', 'again', 'against', 'ain']

In [56]:
[sw for sw in stopwords if len(sw) == 1]

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [57]:
tokens = ['House', 'Visitor', 'Center']
normalized_tokens = [x.lower() for x in tokens]
print(normalized_tokens)

['house', 'visitor', 'center']

In [59]:
def stem(phrase):
    return ' '.join([re.findall('^(.*ss|.*?)(s)?$',
                                word)[0][0].strip("'") for word in phrase.lower().split()])
stem('houses')

'house'

In [60]:
stem("Doctor House's calls")

'doctor house call'

In [61]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
' '.join([stemmer.stem(w).strip("'") for w in "dish washer's fairly washed dishes".split()])

'dish washer fairli wash dish'

In [62]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer(language='english')
' '.join([stemmer.stem(w).strip("'") for w in "dish washer's fairly washed dishes".split()])

'dish washer fair wash dish'

In [66]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\throw\Study\Minico
[nltk_data]     nda\miniconda3\envs\nlpia2\nltk_data...

True

In [64]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to C:\Users\throw\Study\Minico
[nltk_data]     nda\miniconda3\envs\nlpia2\nltk_data...

True

In [70]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize("better")

'better'

In [71]:
lemmatizer.lemmatize("better", pos="a")

'good'

In [72]:
lemmatizer.lemmatize("good", pos="a")

'good'

In [73]:
lemmatizer.lemmatize("goods", pos="a")

'goods'

In [74]:
lemmatizer.lemmatize("goods", pos="n")

'good'

In [75]:
lemmatizer.lemmatize("goodness", pos="n")

'goodness'

In [76]:
lemmatizer.lemmatize("best", pos="a")

'best'

In [67]:
stemmer.stem('goodness')

'good'

In [68]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("better good goods goodness best")
for token in doc:
    print(token.text, token.lemma_)

better well
good good
goods good
goodness goodness
best good

In [1]:
import jieba
seg_list = jieba.cut("西安是一座举世闻名的文化古城")
list(seg_list)

C:\Users\throw\Study\Miniconda\miniconda3\envs\nlpia2\lib\site-packages\jieba\_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\throw\AppData\Local\Temp\jieba.cache
Loading model cost 1.077 seconds.
Prefix dict has been built successfully.

['西安', '是', '一座', '举世闻名', '的', '文化', '古城']

In [2]:
#accurate mode
seg_list = jieba.cut("西安是一座举世闻名的文化古城", cut_all=True)
list(seg_list)

['西安', '是', '一座', '举世', '举世闻名', '闻名', '的', '文化', '古城']

In [22]:
import pandas as pd
onehot_vectors = np.zeros((len(tokens), vocab_size), int)
for i, tok in enumerate(tokens):
    if tok not in vocab:
        continue
    onehot_vectors[i, vocab.index(tok)] = 1
df_onehot = pd.DataFrame(onehot_vectors, columns=vocab)
df_onehot.shape

(18, 15)

In [23]:
df_onehot.iloc[:,:8].replace(0, '')

    ,  . Survival There's adequate as fittest maybe
0                       1
1
2
3
4                                   1
5
6
7
8                                           1
9      1
10              1
11
12
13
14                               1
15  1
16                                                1
17     1

In [24]:
bow = sorted(set(re.findall(pattern, text)))
bow[:9]

[',', '.', 'Liesel', 'Trust', 'and', 'arrived', 'clouds', 'hands', 'her']

In [26]:
bow[9:19]

['hold', 'in', 'like', 'me', 'on', 'out', 'rain', 'she', 'the', 'their']

In [27]:
bow[19:27]

['them', 'they', 'though', 'way', 'were', 'when', 'words', 'would']

In [28]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\throw\study\miniconda\miniconda3\envs\nlpia2\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\throw\study\miniconda\miniconda3\envs\nlpia2\lib\site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\throw\study\miniconda\miniconda3\envs\nlpia2\lib\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\throw\study\miniconda\miniconda3\envs\nlpia2\lib\site-packages (from requests->vaderSentiment) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\throw\study\miniconda\miniconda3\envs\nlpia2\lib\site-packages (from requests->vaderSentiment) (2026.2.25)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sa = SentimentIntensityAnalyzer()
sa.lexicon

{'$:': -1.5,
 '%)': -0.4,
 '%-)': -1.5,
 '&-:': -0.4,
 '&:': -0.7,
 "( '}{' )": 1.6,
 '(%': -0.9,
 "('-:": 2.2,
 "(':": 2.3,
 '((-:': 2.1,
 '(*': 1.1,
 '(-%': -0.7,
 '(-*': 1.3,
 '(-:': 1.6,
 '(-:0': 2.8,
 '(-:<': -0.4,
 '(-:o': 1.5,
 '(-:O': 1.5,
 '(-:{': -0.1,
 '(-:|>*': 1.9,
 '(-;': 1.3,
 '(-;|': 2.1,
 '(8': 2.6,
 '(:': 2.2,
 '(:0': 2.4,
 '(:<': -0.2,
 '(:o': 2.5,
 '(:O': 2.5,
 '(;': 1.1,
 '(;<': 0.3,
 '(=': 2.2,
 '(?:': 2.1,
 '(^:': 1.5,
 '(^;': 1.5,
 '(^;0': 2.0,
 '(^;o': 1.9,
 '(o:': 1.6,
 ")':": -2.0,
 ")-':": -2.1,
 ')-:': -2.1,
 ')-:<': -2.2,
 ')-:{': -2.1,
 '):': -1.8,
 '):<': -1.9,
 '):{': -2.3,
 ');<': -2.6,
 '*)': 0.6,
 '*-)': 0.3,
 '*-:': 2.1,
 '*-;': 2.4,
 '*:': 1.9,
 '*<|:-)': 1.6,
 '*\\0/*': 2.3,
 '*^:': 1.6,
 ',-:': 1.2,
 "---'-;-{@": 2.3,
 '--<--<@': 2.2,
 '.-:': -1.2,
 '..###-:': -1.7,
 '..###:': -1.9,
 '/-:': -1.3,
 '/:': -1.3,
 '/:<': -1.4,
 '/=': -0.9,
 '/^:': -1.0,
 '/o:': -1.4,
 '0-8': 0.1,
 '0-|': -1.2,
 '0:)': 1.9,
 '0:-)': 1.4,
 '0:-3': 1.5,
 '0:03': 1.9,
 '0;^)': 1.6,
 '0_o': -0.3,
 '10q': 2.1,
 '1337': 2.1,
 '143': 3.2,
 '1432': 2.6,
 '14aa41': 2.4,
 '182': -2.9,
 '187': -3.1,
 '2g2b4g': 2.8,
 '2g2bt': -0.1,
 '2qt': 2.1,
 '3:(': -2.2,
 '3:)': 0.5,
 '3:-(': -2.3,
 '3:-)': -1.4,
 '4col': -2.2,
 '4q': -3.1,
 '5fs': 1.5,
 '8)': 1.9,
 '8-d': 1.7,
 '8-o': -0.3,
 '86': -1.6,
 '8d': 2.9,
 ':###..': -2.4,
 ':$': -0.2,
 ':&': -0.6,
 ":'(": -2.2,
 ":')": 2.3,
 ":'-(": -2.4,
 ":'-)": 2.7,
 ':(': -1.9,
 ':)': 2.0,
 ':*': 2.5,
 ':-###..': -2.5,
 ':-&': -0.5,
 ':-(': -1.5,
 ':-)': 1.3,
 ':-))': 2.8,
 ':-*': 1.7,
 ':-,': 1.1,
 ':-.': -0.9,
 ':-/': -1.2,
 ':-<': -1.5,
 ':-d': 2.3,
 ':-D': 2.3,
 ':-o': 0.1,
 ':-p': 1.5,
 ':-[': -1.6,
 ':-\\': -0.9,
 ':-c': -1.3,
 ':-|': -0.7,
 ':-||': -2.5,
 ':-Þ': 0.9,
 ':/': -1.4,
 ':3': 2.3,
 ':<': -2.1,
 ':>': 2.1,
 ':?)': 1.3,
 ':?c': -1.6,
 ':@': -2.5,
 ':d': 2.3,
 ':D': 2.3,
 ':l': -1.7,
 ':o': -0.4,
 ':p': 1.0,
 ':s': -1.2,
 ':[': -2.0,
 ':\\': -1.3,
 ':]': 2.2,
 ':^)': 2.1,
 ':^*': 2.6,
 ':^/': -1.2,
 ':^\\': -1.0,
 ':^|': -1.0,
 ':c': -2.1,
 ':c)': 2.0,
 ':o)': 2.1,
 ':o/': -1.4,
 ':o\\': -1.1,
 ':o|': -0.6,
 ':P': 1.4,
 ':{': -1.9,
 ':|': -0.4,
 ':}': 2.1,
 ':Þ': 1.1,
 ';)': 0.9,
 ';-)': 1.0,
 ';-*': 2.2,
 ';-]': 0.7,
 ';d': 0.8,
 ';D': 0.8,
 ';]': 0.6,
 ';^)': 1.4,
 '</3': -3.0,
 '<3': 1.9,
 '<:': 2.1,
 '<:-|': -1.4,
 '=)': 2.2,
 '=-3': 2.0,
 '=-d': 2.4,
 '=-D': 2.4,
 '=/': -1.4,
 '=3': 2.1,
 '=d': 2.3,
 '=D': 2.3,
 '=l': -1.2,
 '=\\': -1.2,
 '=]': 1.6,
 '=p': 1.3,
 '=|': -0.8,
 '>-:': -2.0,
 '>.<': -1.3,
 '>:': -2.1,
 '>:(': -2.7,
 '>:)': 0.4,
 '>:-(': -2.7,
 '>:-)': -0.4,
 '>:/': -1.6,
 '>:o': -1.2,
 '>:p': 1.0,
 '>:[': -2.1,
 '>:\\': -1.7,
 '>;(': -2.9,
 '>;)': 0.1,
 '>_>^': 2.1,
 '@:': -2.1,
 '@>-->--': 2.1,
 "@}-;-'---": 2.2,
 'aas': 2.5,
 'aayf': 2.7,
 'afu': -2.9,
 'alol': 2.8,
 'ambw': 2.9,
 'aml': 3.4,
 'atab': -1.9,
 'awol': -1.3,
 'ayc': 0.2,
 'ayor': -1.2,
 'aug-00': 0.3,
 'bfd': -2.7,
 'bfe': -2.6,
 'bff': 2.9,
 'bffn': 1.0,
 'bl': 2.3,
 'bsod': -2.2,
 'btd': -2.1,
 'btdt': -0.1,
 'bz': 0.4,
 'b^d': 2.6,
 'cwot': -2.3,
 "d-':": -2.5,
 'd8': -3.2,
 'd:': 1.2,
 'd:<': -3.2,
 'd;': -2.9,
 'd=': 1.5,
 'doa': -2.3,
 'dx': -3.0,
 'ez': 1.5,
 'fav': 2.0,
 'fcol': -1.8,
 'ff': 1.8,
 'ffs': -2.8,
 'fkm': -2.4,
 'foaf': 1.8,
 'ftw': 2.0,
 'fu': -3.7,
 'fubar': -3.0,
 'fwb': 2.5,
 'fyi': 0.8,
 'fysa': 0.4,
 'g1': 1.4,
 'gg': 1.2,
 'gga': 1.7,
 'gigo': -0.6,
 'gj': 2.0,
 'gl': 1.3,
 'gla': 2.5,
 'gn': 1.2,
 'gr8': 2.7,
 'grrr': -0.4,
 'gt': 1.1,
 'h&k': 2.3,
 'hagd': 2.2,
 'hagn': 2.2,
 'hago': 1.2,
 'hak': 1.9,
 'hand': 2.2,
 'heart': 3.2,
 'hearts': 3.3,
 'hho1/2k': 1.4,
 'hhoj': 2.0,
 'hhok': 0.9,
 'hugz': 2.0,
 'hi5': 1.9,
 'idk': -0.4,
 'ijs': 0.7,
 'ilu': 3.4,
 'iluaaf': 2.7,
 'ily': 3.4,
 'ily2': 2.6,
 'iou': 0.7,
 'iyq': 2.3,
 'j/j': 2.0,
 'j/k': 1.6,
 'j/p': 1.4,
 'j/t': -0.2,
 'j/w': 1.0,
 'j4f': 1.4,
 'j4g': 1.7,
 'jho': 0.8,
 'jhomf': 1.0,
 'jj': 1.0,
 'jk': 0.9,
 'jp': 0.8,
 'jt': 0.9,
 'jw': 1.6,
 'jealz': -1.2,
 'k4y': 2.3,
 'kfy': 2.3,
 'kia': -3.2,
 'kk': 1.5,
 'kmuf': 2.2,
 'l': 2.0,
 'l&r': 2.2,
 'laoj': 1.3,
 'lmao': 2.9,
 'lmbao': 1.8,
 'lmfao': 2.5,
 'lmso': 2.7,
 'lol': 1.8,
 'lolz': 2.7,
 'lts': 1.6,
 'ly': 2.6,
 'ly4e': 2.7,
 'lya': 3.3,
 'lyb': 3.0,
 'lyl': 3.1,
 'lylab': 2.7,
 'lylas': 2.6,
 'lylb': 1.6,
 'm8': 1.4,
 'mia': -1.2,
 'mml': 2.0,
 'mofo': -2.4,
 'muah': 2.3,
 'mubar': -1.0,
 'musm': 0.9,
 'mwah': 2.5,
 'n1': 1.9,
 'nbd': 1.3,
 'nbif': -0.5,
 'nfc': -2.7,
 'nfw': -2.4,
 'nh': 2.2,
 'nimby': -0.8,
 'nimjd': -0.7,
 'nimq': -0.2,
 'nimy': -1.4,
 'nitl': -1.5,
 'nme': -2.1,
 'noyb': -0.7,
 'np': 1.4,
 'ntmu': 1.4,
 'o-8': -0.5,
 'o-:': -0.3,
 'o-|': -1.1,
 'o.o': -0.8,
 'O.o': -0.6,
 'o.O': -0.6,
 'o:': -0.2,
 'o:)': 1.5,
 'o:-)': 2.0,
 'o:-3': 2.2,
 'o:3': 2.3,
 'o:<': -0.3,
 'o;^)': 1.6,
 'ok': 1.2,
 'o_o': -0.5,
 'O_o': -0.5,
 'o_O': -0.5,
 'pita': -2.4,
 'pls': 0.3,
 'plz': 0.3,
 'pmbi': 0.8,
 'pmfji': 0.3,
 'pmji': 0.7,
 'po': -2.6,
 'ptl': 2.6,
 'pu': -1.1,
 'qq': -2.2,
 'qt': 1.8,
 'r&r': 2.4,
 'rofl': 2.7,
 'roflmao': 2.5,
 'rotfl': 2.6,
 'rotflmao': 2.8,
 'rotflmfao': 2.5,
 'rotflol': 3.0,
 'rotgl': 2.9,
 'rotglmao': 1.8,
 's:': -1.1,
 'sapfu': -1.1,
 'sete': 2.8,
 'sfete': 2.7,
 'sgtm': 2.4,
 'slap': 0.6,
 'slaw': 2.1,
 'smh': -1.3,
 'snafu': -2.5,
 'sob': -1.0,
 'swak': 2.3,
 'tgif': 2.3,
 'thks': 1.4,
 'thx': 1.5,
 'tia': 2.3,
 'tmi': -0.3,
 'tnx': 1.1,
 'true': 1.8,
 'tx': 1.5,
 'txs': 1.1,
 'ty': 1.6,
 'tyvm': 2.5,
 'urw': 1.9,
 'vbg': 2.1,
 'vbs': 3.1,
 'vip': 2.3,
 'vwd': 2.6,
 'vwp': 2.1,
 'wag': -0.2,
 'wd': 2.7,
 'wilco': 0.9,
 'wp': 1.0,
 'wtf': -2.8,
 'wtg': 2.1,
 'wth': -2.4,
 'x-d': 2.6,
 'x-p': 1.7,
 'xd': 2.8,
 'xlnt': 3.0,
 'xoxo': 3.0,
 'xoxozzz': 2.3,
 'xp': 1.6,
 'xqzt': 1.6,
 'xtc': 0.8,
 'yolo': 1.1,
 'yoyo': 0.4,
 'yvw': 1.6,
 'yw': 1.8,
 'ywia': 2.5,
 'zzz': -1.2,
 '[-;': 0.5,
 '[:': 1.3,
 '[;': 1.0,
 '[=': 1.7,
 '\\-:': -1.0,
 '\\:': -1.0,
 '\\:<': -1.7,
 '\\=': -1.1,
 '\\^:': -1.3,
 '\\o/': 2.2,
 '\\o:': -1.2,
 ']-:': -2.1,
 ']:': -1.6,
 ']:<': -2.5,
 '^<_<': 1.4,
 '^urs': -2.8,
 'abandon': -1.9,
 'abandoned': -2.0,
 'abandoner': -1.9,
 'abandoners': -1.9,
 'abandoning': -1.6,
 'abandonment': -2.4,
 'abandonments': -1.7,
 'abandons': -1.3,
 'abducted': -2.3,
 'abduction': -2.8,
 'abductions': -2.0,
 'abhor': -2.0,
 'abhorred': -2.4,
 'abhorrent': -3.1,
 'abhors': -2.9,
 'abilities': 1.0,
 'ability': 1.3,
 'aboard': 0.1,
 'absentee': -1.1,
 'absentees': -0.8,
 'absolve': 1.2,
 'absolved': 1.5,
 'absolves': 1.3,
 'absolving': 1.6,
 'abuse': -3.2,
 'abused': -2.3,
 'abuser': -2.6,
 'abusers': -2.6,
 'abuses': -2.6,
 'abusing': -2.0,
 'abusive': -3.2,
 'abusively': -2.8,
 'abusiveness': -2.5,
 'abusivenesses': -3.0,
 'accept': 1.6,
 'acceptabilities': 1.6,
 'acceptability': 1.1,
 'acceptable': 1.3,
 'acceptableness': 1.3,
 'acceptably': 1.5,
 'acceptance': 2.0,
 'acceptances': 1.7,
 'acceptant': 1.6,
 'acceptation': 1.3,
 'acceptations': 0.9,
 'accepted': 1.1,
 'accepting': 1.6,
 'accepts': 1.3,
 'accident': -2.1,
 'accidental': -0.3,
 'accidentally': -1.4,
 'accidents': -1.3,
 'accomplish': 1.8,
 'accomplished': 1.9,
 'accomplishes': 1.7,
 'accusation': -1.0,
 'accusations': -1.3,
 'accuse': -0.8,
 'accused': -1.2,
 'accuses': -1.4,
 'accusing': -0.7,
 'ache': -1.6,
 'ached': -1.6,
 'aches': -1.0,
 'achievable': 1.3,
 'aching': -2.2,
 'acquit': 0.8,
 'acquits': 0.1,
 'acquitted': 1.0,
 'acquitting': 1.3,
 'acrimonious': -1.7,
 'active': 1.7,
 'actively': 1.3,
 'activeness': 0.6,
 'activenesses': 0.8,
 'actives': 1.1,
 'adequate': 0.9,
 'admirability': 2.4,
 'admirable': 2.6,
 'admirableness': 2.2,
 'admirably': 2.5,
 'admiral': 1.3,
 'admirals': 1.5,
 'admiralties': 1.6,
 'admiralty': 1.2,
 'admiration': 2.5,
 'admirations': 1.6,
 'admire': 2.1,
 'admired': 2.3,
 'admirer': 1.8,
 'admirers': 1.7,
 'admires': 1.5,
 'admiring': 1.6,
 'admiringly': 2.3,
 'admit': 0.8,
 'admits': 1.2,
 'admitted': 0.4,
 'admonished': -1.9,
 'adopt': 0.7,
 'adopts': 0.7,
 'adorability': 2.2,
 'adorable': 2.2,
 'adorableness': 2.5,
 'adorably': 2.1,
 'adoration': 2.9,
 'adorations': 2.2,
 'adore': 2.6,
 'adored': 1.8,
 'adorer': 1.7,
 'adorers': 2.1,
 'adores': 1.6,
 'adoring': 2.6,
 'adoringly': 2.4,
 'adorn': 0.9,
 'adorned': 0.8,
 'adorner': 1.3,
 'adorners': 0.9,
 'adorning': 1.0,
 'adornment': 1.3,
 'adornments': 0.8,
 'adorns': 0.5,
 'advanced': 1.0,
 'advantage': 1.0,
 'advantaged': 1.4,
 'advantageous': 1.5,
 'advantageously': 1.9,
 'advantageousness': 1.6,
 'advantages': 1.5,
 'advantaging': 1.6,
 'adventure': 1.3,
 'adventured': 1.3,
 'adventurer': 1.2,
 'adventurers': 0.9,
 'adventures': 1.4,
 'adventuresome': 1.7,
 'adventuresomeness': 1.3,
 'adventuress': 0.8,
 'adventuresses': 1.4,
 'adventuring': 2.3,
 'adventurism': 1.5,
 'adventurist': 1.4,
 'adventuristic': 1.7,
 'adventurists': 1.2,
 'adventurous': 1.4,
 'adventurously': 1.3,
 'adventurousness': 1.8,
 'adversarial': -1.5,
 'adversaries': -1.0,
 'adversary': -0.8,
 'adversative': -1.2,
 'adversatively': -0.1,
 'adversatives': -1.0,
 'adverse': -1.5,
 'adversely': -0.8,
 'adverseness': -0.6,
 'adversities': -1.5,
 'adversity': -1.8,
 'affected': -0.6,
 'affection': 2.4,
 'affectional': 1.9,
 'affectionally': 1.5,
 'affectionate': 1.9,
 'affectionately': 2.2,
 'affectioned': 1.8,
 'affectionless': -2.0,
 'affections': 1.5,
 'afflicted': -1.5,
 'affronted': 0.2,
 'aggravate': -2.5,
 'aggravated': -1.9,
 'aggravates': -1.9,
 'aggravating': -1.2,
 'aggress': -1.3,
 'aggressed': -1.4,
 'aggresses': -0.5,
 'aggressing': -0.6,
 'aggression': -1.2,
 'aggressions': -1.3,
 'aggressive': -0.6,
 'aggressively': -1.3,
 'aggressiveness': -1.8,
 'aggressivities': -1.4,
 'aggressivity': -0.6,
 'aggressor': -0.8,
 'aggressors': -0.9,
 'aghast': -1.9,
 'agitate': -1.7,
 'agitated': -2.0,
 'agitatedly': -1.6,
 'agitates': -1.4,
 'agitating': -1.8,
 'agitation': -1.0,
 'agitational': -1.2,
 'agitations': -1.3,
 'agitative': -1.3,
 'agitato': -0.1,
 'agitator': -1.4,
 'agitators': -2.1,
 'agog': 1.9,
 'agonise': -2.1,
 'agonised': -2.3,
 'agonises': -2.4,
 'agonising': -1.5,
 'agonize': -2.3,
 'agonized': -2.2,
 'agonizes': -2.3,
 'agonizing': -2.7,
 'agonizingly': -2.3,
 'agony': -1.8,
 'agree': 1.5,
 'agreeability': 1.9,
 'agreeable': 1.8,
 'agreeableness': 1.8,
 'agreeablenesses': 1.3,
 'agreeably': 1.6,
 'agreed': 1.1,
 'agreeing': 1.4,
 'agreement': 2.2,
 'agreements': 1.1,
 'agrees': 0.8,
 'alarm': -1.4,
 'alarmed': -1.4,
 'alarming': -0.5,
 'alarmingly': -2.6,
 'alarmism': -0.3,
 'alarmists': -1.1,
 'alarms': -1.1,
 'alas': -1.1,
 'alert': 1.2,
 'alienation': -1.1,
 'alive': 1.6,
 'allergic': -1.2,
 'allow': 0.9,
 'alone': -1.0,
 'alright': 1.0,
 'amaze': 2.5,
 'amazed': 2.2,
 'amazedly': 2.1,
 'amazement': 2.5,
 'amazements': 2.2,
 'amazes': 2.2,
 'amazing': 2.8,
 'amazon': 0.7,
 'amazonite': 0.2,
 'amazons': -0.1,
 'amazonstone': 1.0,
 'amazonstones': 0.2,
 'ambitious': 2.1,
 'ambivalent': 0.5,
 'amor': 3.0,
 'amoral': -1.6,
 'amoralism': -0.7,
 'amoralisms': -0.7,
 'amoralities': -1.2,
 'amorality': -1.5,
 'amorally': -1.0,
 'amoretti': 0.2,
 'amoretto': 0.6,
 'amorettos': 0.3,
 'amorino': 1.2,
 'amorist': 1.6,
 'amoristic': 1.0,
 'amorists': 0.1,
 'amoroso': 2.3,
 'amorous': 1.8,
 'amorously': 2.3,
 'amorousness': 2.0,
 'amorphous': -0.2,
 'amorphously': 0.1,
 'amorphousness': 0.3,
 'amort': -2.1,
 'amortise': 0.5,
 'amortised': -0.2,
 'amortises': 0.1,
 'amortizable': 0.5,
 'amortization': 0.6,
 'amortizations': 0.2,
 'amortize': -0.1,
 'amortized': 0.8,
 'amortizes': 0.6,
 'amortizing': 0.8,
 'amusable': 0.7,
 'amuse': 1.7,
 'amused': 1.8,
 'amusedly': 2.2,
 'amusement': 1.5,
 'amusements': 1.5,
 'amuser': 1.1,
 'amusers': 1.3,
 'amuses': 1.7,
 'amusia': 0.3,
 'amusias': -0.4,
 'amusing': 1.6,
 'amusingly': 0.8,
 'amusingness': 1.8,
 'amusive': 1.7,
 'anger': -2.7,
 'angered': -2.3,
 'angering': -2.2,
 'angerly': -1.9,
 'angers': -2.3,
 'angrier': -2.3,
 'angriest': -3.1,
 'angrily': -1.8,
 'angriness': -1.7,
 'angry': -2.3,
 'anguish': -2.9,
 'anguished': -1.8,
 'anguishes': -2.1,
 'anguishing': -2.7,
 'animosity': -1.9,
 'annoy': -1.9,
 'annoyance': -1.3,
 'annoyances': -1.8,
 'annoyed': -1.6,
 'annoyer': -2.2,
 'annoyers': -1.5,
 'annoying': -1.7,
 'annoys': -1.8,
 'antagonism': -1.9,
 'antagonisms': -1.2,
 'antagonist': -1.9,
 'antagonistic': -1.7,
 'antagonistically': -2.2,
 'antagonists': -1.7,
 'antagonize': -2.0,
 'antagonized': -1.4,
 'antagonizes': -0.5,
 'antagonizing': -2.7,
 'anti': -1.3,
 'anticipation': 0.4,
 'anxieties': -0.6,
 'anxiety': -0.7,
 'anxious': -1.0,
 'anxiously': -0.9,
 'anxiousness': -1.0,
 'aok': 2.0,
 'apathetic': -1.2,
 'apathetically': -0.4,
 'apathies': -0.6,
 'apathy': -1.2,
 'apeshit': -0.9,
 'apocalyptic': -3.4,
 'apologise': 1.6,
 'apologised': 0.4,
 'apologises': 0.8,
 'apologising': 0.2,
 'apologize': 0.4,
 'apologized': 1.3,
 'apologizes': 1.5,
 'apologizing': -0.3,
 'apology': 0.2,
 'appall': -2.4,
 'appalled': -2.0,
 'appalling': -1.5,
 'appallingly': -2.0,
 'appalls': -1.9,
 'appease': 1.1,
 'appeased': 0.9,
 'appeases': 0.9,
 'appeasing': 1.0,
 'applaud': 2.0,
 'applauded': 1.5,
 'applauding': 2.1,
 'applauds': 1.4,
 'applause': 1.8,
 'appreciate': 1.7,
 'appreciated': 2.3,
 'appreciates': 2.3,
 'appreciating': 1.9,
 'appreciation': 2.3,
 'appreciations': 1.7,
 'appreciative': 2.6,
 'appreciatively': 1.8,
 'appreciativeness': 1.6,
 'appreciator': 2.6,
 'appreciators': 1.5,
 'appreciatory': 1.7,
 'apprehensible': 1.1,
 'apprehensibly': -0.2,
 'apprehension': -2.1,
 'apprehensions': -0.9,
 'apprehensively': -0.3,
 'apprehensiveness': -0.7,
 'approval': 2.1,
 'approved': 1.8,
 'approves': 1.7,
 'ardent': 2.1,
 'arguable': -1.0,
 'arguably': -1.0,
 'argue': -1.4,
 'argued': -1.5,
 'arguer': -1.6,
 'arguers': -1.4,
 'argues': -1.6,
 'arguing': -2.0,
 'argument': -1.5,
 'argumentative': -1.5,
 'argumentatively': -1.8,
 'argumentive': -1.5,
 'arguments': -1.7,
 'arrest': -1.4,
 'arrested': -2.1,
 'arrests': -1.9,
 'arrogance': -2.4,
 'arrogances': -1.9,
 'arrogant': -2.2,
 'arrogantly': -1.8,
 'ashamed': -2.1,
 'ashamedly': -1.7,
 'ass': -2.5,
 'assassination': -2.9,
 'assassinations': -2.7,
 'assault': -2.8,
 'assaulted': -2.4,
 'assaulting': -2.3,
 'assaultive': -2.8,
 'assaults': -2.5,
 'asset': 1.5,
 'assets': 0.7,
 'assfucking': -2.5,
 'assholes': -2.8,
 'assurance': 1.4,
 'assurances': 1.4,
 'assure': 1.4,
 'assured': 1.5,
 'assuredly': 1.6,
 'assuredness': 1.4,
 'assurer': 0.9,
 'assurers': 1.1,
 'assures': 1.3,
 'assurgent': 1.3,
 'assuring': 1.6,
 'assuror': 0.5,
 'assurors': 0.7,
 'astonished': 1.6,
 'astound': 1.7,
 'astounded': 1.8,
 'astounding': 1.8,
 'astoundingly': 2.1,
 'astounds': 2.1,
 'attachment': 1.2,
 'attachments': 1.1,
 'attack': -2.1,
 'attacked': -2.0,
 'attacker': -2.7,
 'attackers': -2.7,
 'attacking': -2.0,
 'attacks': -1.9,
 'attract': 1.5,
 'attractancy': 0.9,
 'attractant': 1.3,
 'attractants': 1.4,
 'attracted': 1.8,
 'attracting': 2.1,
 'attraction': 2.0,
 'attractions': 1.8,
 'attractive': 1.9,
 'attractively': 2.2,
 'attractiveness': 1.8,
 'attractivenesses': 2.1,
 'attractor': 1.2,
 'attractors': 1.2,
 'attracts': 1.7,
 'audacious': 0.9,
 'authority': 0.3,
 'aversion': -1.9,
 'aversions': -1.1,
 'aversive': -1.6,
 'aversively': -0.8,
 'avert': -0.7,
 'averted': -0.3,
 'averts': -0.4,
 'avid': 1.2,
 'avoid': -1.2,
 'avoidance': -1.7,
 'avoidances': -1.1,
 'avoided': -1.4,
 'avoider': -1.8,
 'avoiders': -1.4,
 'avoiding': -1.4,
 'avoids': -0.7,
 'await': 0.4,
 'awaited': -0.1,
 'awaits': 0.3,
 'award': 2.5,
 'awardable': 2.4,
 'awarded': 1.7,
 'awardee': 1.8,
 'awardees': 1.2,
 'awarder': 0.9,
 'awarders': 1.3,
 'awarding': 1.9,
 'awards': 2.0,
 'awesome': 3.1,
 'awful': -2.0,
 'awkward': -0.6,
 'awkwardly': -1.3,
 'awkwardness': -0.7,
 'axe': -0.4,
 'axed': -1.3,
 'backed': 0.1,
 'backing': 0.1,
 'backs': -0.2,
 'bad': -2.5,
 'badass': 1.4,
 'badly': -2.1,
 'bailout': -0.4,
 'bamboozle': -1.5,
 'bamboozled': -1.5,
 'bamboozles': -1.5,
 'ban': -2.6,
 'banish': -1.9,
 'bankrupt': -2.6,
 'bankster': -2.1,
 'banned': -2.0,
 'bargain': 0.8,
 'barrier': -0.5,
 'bashful': -0.1,
 'bashfully': 0.2,
 'bashfulness': -0.8,
 'bastard': -2.5,
 'bastardies': -1.8,
 'bastardise': -2.1,
 'bastardised': -2.3,
 'bastardises': -2.3,
 'bastardising': -2.6,
 'bastardization': -2.4,
 'bastardizations': -2.1,
 'bastardize': -2.4,
 'bastardized': -2.0,
 'bastardizes': -1.8,
 'bastardizing': -2.3,
 'bastardly': -2.7,
 'bastards': -3.0,
 'bastardy': -2.7,
 'battle': -1.6,
 'battled': -1.2,
 'battlefield': -1.6,
 'battlefields': -0.9,
 'battlefront': -1.2,
 'battlefronts': -0.8,
 'battleground': -1.7,
 'battlegrounds': -0.6,
 'battlement': -0.4,
 'battlements': -0.4,
 'battler': -0.8,
 'battlers': -0.2,
 'battles': -1.6,
 'battleship': -0.1,
 'battleships': -0.5,
 'battlewagon': -0.3,
 'battlewagons': -0.5,
 'battling': -1.1,
 'beaten': -1.8,
 'beatific': 1.8,
 'beating': -2.0,
 'beaut': 1.6,
 'beauteous': 2.5,
 'beauteously': 2.6,
 ...}

In [3]:
[(tok, score) for tok, score in sa.lexicon.items() if " " in tok]

[("( '}{' )", 1.6),
 ("can't stand", -2.0),
 ('fed up', -1.8),
 ('screwed up', -1.5)]

In [4]:
sa.polarity_scores(text="Python is very readable and it's great for NLP.")

{'neg': 0.0, 'neu': 0.661, 'pos': 0.339, 'compound': 0.6249}

In [5]:
sa.polarity_scores(text="Python is not a bad choice for most applications.")

{'neg': 0.0, 'neu': 0.737, 'pos': 0.263, 'compound': 0.431}

In [7]:
corpus = ["Absolutely perfect! Love it! :-) :-) :-)", "Horrible! Completely useless. :(",
          "It was OK. Some good and some bad things."]
for doc in corpus:
    scores = sa.polarity_scores(doc)
    print('{:+}: {}'.format(scores['compound'], doc))

+0.9428: Absolutely perfect! Love it! :-) :-) :-)
-0.8768: Horrible! Completely useless. :(
-0.1531: It was OK. Some good and some bad things.

In [9]:
import pandas as pd
movies = pd.read_csv('https://proai.org/movie-reviews.csv.gz', index_col=0)
movies.head().round(2)

    sentiment                                               text
id
1        2.27  The Rock is destined to be the 21st Century's ...
2        3.53  The gorgeously elaborate continuation of ''The...
3       -0.60                     Effective but too tepid biopic
4        1.47  If you sometimes like to go to the movies to h...
5        1.73  Emerges as something rare, an issue movie that...

In [10]:
movies.describe().round(2)

       sentiment
count   10605.00
mean        0.00
std         1.92
min        -3.88
25%        -1.77
50%        -0.08
75%         1.83
max         3.94

In [11]:
pd.options.display.width = 75
from nltk.tokenize import casual_tokenize
bows = []
from collections import Counter
for text in movies.text:
    bows.append(Counter(casual_tokenize(text)))
df_movies = pd.DataFrame.from_records(bows)
df_movies = df_movies.fillna(0).astype(int)
df_movies.shape

(10605, 20756)

In [15]:
df_movies.head()

,The,Rock,is,destined,to,be,the,21st,Century's,new,...,Ill,slummer,Rashomon,dipsticks,Bearable,Staggeringly,’,ve,muttering,dissing
0,1,1,1,1,2,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,4,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df_movies.head()[list(bows[0].keys())]

,The,Rock,is,destined,to,be,the,21st,Century's,new,...,Schwarzenegger,",",Jean,Claud,Van,Damme,or,Steven,Segal,.
0,1,1,1,1,2,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,2,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,4
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,4,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [21]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb = nb.fit(df_movies, movies.sentiment > 0)
movies['pred_senti'] = (
    nb.predict_proba(df_movies))[:, 1] * 8 - 4
movies['error'] = movies.pred_senti - movies.sentiment
mae = movies['error'].abs().mean().round(1) #Mean Absolute Error
mae

1.9

In [23]:
movies['senti_ispos'] = (movies['sentiment'] > 0).astype(int)
movies['pred_ispos'] = (movies['pred_senti'] > 0).astype(int)
columns = [c for c in movies.columns if 'senti' in c or 'pred' in c]
movies[columns].head(8)

    sentiment  pred_senti  senti_ispos  pred_ispos
id
1    2.266667    2.511515            1           1
2    3.533333    3.999904            1           1
3   -0.600000   -3.655976            0           0
4    1.466667    1.940954            1           1
5    1.733333    3.910373            1           1
6    2.533333    3.995188            1           1
7    2.466667    3.960466            1           1
8    1.266667   -1.918701            1           0

In [19]:
(movies.pred_ispos == movies.senti_ispos).sum() / len(movies)

0.9344648750589345

In [24]:
products = pd.read_csv('https://proai.org/product-reviews.csv.gz')
products.columns

Index(['id', 'sentiment', 'text'], dtype='object')

In [25]:
products.head()

    id  sentiment                                               text
0  1_1      -0.90  troubleshooting ad-2500 and ad-2600 no picture...
1  1_2      -0.15  repost from january 13, 2004 with a better fit...
2  1_3      -0.20  does your apex dvd player only play dvd audio ...
3  1_4      -0.10  or does it play audio and video but scrolling ...
4  1_5      -0.50  before you try to return the player or waste h...

In [26]:
bows = []
for text in products['text']:
    bows.append(Counter(casual_tokenize(text)))
df_products = pd.DataFrame.from_records(bows)
df_products = df_products.fillna(0).astype(int)
df_products.shape

(3546, 5687)

In [27]:
df_all_bows = pd.concat([df_movies, df_products])
df_all_bows.columns

Index(['The', 'Rock', 'is', 'destined', 'to', 'be', 'the', '21st',
       'Century's', 'new',
       ...
       'sligtly', 'owner', '81', 'defectively', 'warrranty', 'expire',
       'expired', 'voids', 'baghdad', 'harddisk'],
      dtype='object', length=23302)

In [30]:
vocab = list(df_movies.columns)
df_products = df_all_bows.iloc[len(movies):]
df_products = df_products[vocab]
df_products = df_products.fillna(0).astype(int)
df_products.shape

(3546, 20756)

In [29]:
df_movies.shape

(10605, 20756)

In [31]:
products['senti_ispos'] = (products['sentiment'] > 0).astype(int)
products['pred_ispos'] = nb.predict(df_products).astype(int)
correct = (products['pred_ispos'] == products['senti_ispos'])
correct.sum() / len(products)

0.5572476029328821